/**
 * tokenizer.ts — CST (Cognitive Semantic Tokenizer) for English.
 *
 * Converts raw English text → CSTToken list.
 * Self-contained: no dependencies.
 *
 * Token types:
 *   Core:       CONCEPT | ROLE | REL | LIT
 *   Structural: NEG | QUERY | COND | CAUSE | FUTURE | PAST | MODAL
 *   Question:   WHAT_Q | WHICH_Q | WHERE_Q | WHEN_Q | WHO_Q | WHY_Q | HOW_Q
 */

export type TokenType =
  | "CONCEPT"
  | "ROLE"
  | "REL"
  | "LIT"
  | "NEG"
  | "QUERY"
  | "COND"
  | "CAUSE"
  | "FUTURE"
  | "PAST"
  | "MODAL"
  | "WHAT_Q"
  | "WHICH_Q"
  | "WHERE_Q"
  | "WHEN_Q"
  | "WHO_Q"
  | "WHY_Q"
  | "HOW_Q";

export interface CSTToken {
  type: TokenType;
  value: string; // e.g. "CONCEPT:write", "ROLE:agent", "NEG"
  surface: string; // original word
  field?: string; // semantic field (for CONCEPT tokens)
  role?: string; // morphological role (for ROLE tokens)
}

// ── Vocabulary ────────────────────────────────────────────────────────────────

export const SEMANTIC_FIELDS: Record<string, string> = {
  // Self-mappings
  time: "time",
  place: "place",
  quality: "quality",
  size: "size",
  art: "art",
  sport: "sport",
  color: "color",
  animal: "animal",
  plant: "plant",
  weather: "weather",
  material: "material",

  // Writing / Recording
  write: "write",
  record: "write",
  document: "write",
  note: "write",
  inscribe: "write",
  draft: "write",
  compose: "write",
  author: "write",
  publish: "write",
  print: "write",
  type: "write",
  scribe: "write",
  transcribe: "write",
  log: "write",
  pen: "write",

  // Sending / Communication
  send: "send",
  transmit: "send",
  dispatch: "send",
  forward: "send",
  deliver: "send",
  mail: "send",
  email: "send",
  broadcast: "send",
  relay: "send",
  post: "send",
  ship: "send",
  transfer: "send",
  address: "send",
  media: "send",

  // Knowledge / Learning
  know: "know",
  learn: "know",
  understand: "know",
  study: "know",
  teach: "know",
  educate: "know",
  read: "know",
  discover: "know",
  comprehend: "know",
  grasp: "know",
  realize: "know",
  recognize: "know",
  perceive: "know",
  scholar: "know",
  student: "know",
  learner: "know",

  // Gathering / Meeting
  meet: "gather",
  assemble: "gather",
  collect: "gather",
  join: "gather",
  unite: "gather",
  gather: "gather",
  group: "gather",
  combine: "gather",
  merge: "gather",
  converge: "gather",
  congregate: "gather",

  // Making / Creating
  make: "create",
  build: "create",
  create: "create",
  produce: "create",
  generate: "create",
  form: "create",
  develop: "create",
  design: "create",
  invent: "create",
  manufacture: "create",
  craft: "create",
  establish: "create",
  found: "create",
  construct: "create",
  fabricate: "create",
  construction: "create",

  // Work / Labour
  work: "work",
  labor: "work",
  operate: "work",
  perform: "work",
  execute: "work",
  run: "work",
  function: "work",

  // Movement / Travel
  move: "move",
  go: "move",
  travel: "move",
  walk: "move",
  transport: "move",
  carry: "move",
  bring: "move",
  put: "move",
  arrive: "move",
  depart: "move",
  come: "move",
  leave: "move",
  ride: "move",
  drive: "move",

  // Governing / Control
  govern: "govern",
  rule: "govern",
  control: "govern",
  lead: "govern",
  manage: "govern",
  direct: "govern",
  command: "govern",
  order: "govern",
  administer: "govern",
  regulate: "govern",

  // Speaking / Language
  speak: "speak",
  say: "speak",
  tell: "speak",
  talk: "speak",
  explain: "speak",
  discuss: "speak",
  communicate: "speak",
  announce: "speak",
  declare: "speak",
  express: "speak",
  state: "speak",

  // Thinking / Reasoning
  think: "think",
  reason: "think",
  analyze: "think",
  believe: "think",
  consider: "think",
  judge: "think",
  evaluate: "think",
  assess: "think",
  decide: "think",
  choose: "think",
  determine: "think",

  // Health / Body
  health: "health",
  medicine: "health",
  heal: "health",
  treat: "health",
  disease: "health",
  cure: "health",
  hurt: "health",
  body: "body",

  // Technology
  tech: "tech",
  computer: "tech",
  software: "tech",
  digital: "tech",
  code: "tech",
  program: "tech",
  system: "tech",
  data: "tech",
  online: "tech",
  offline: "tech",

  // Science
  science: "science",
  experiment: "science",
  theory: "science",
  research: "science",
  biology: "science",
  chemistry: "science",
  physics: "science",
  heat: "science",

  // Trade / Economics
  trade: "trade",
  buy: "trade",
  sell: "trade",
  economy: "trade",
  business: "trade",
  market: "trade",
  price: "trade",
  cost: "trade",

  // Fighting / Conflict
  fight: "fight",
  battle: "fight",
  attack: "fight",
  defend: "fight",
  war: "fight",
  military: "fight",
  conflict: "fight",

  // Giving / Sharing
  give: "give",
  share: "give",
  donate: "give",
  grant: "give",
  distribute: "give",
  offer: "give",
  provide: "give",

  // Feeling / Emotion
  feel: "feel",
  love: "feel",
  hate: "feel",
  fear: "feel",
  hope: "feel",
  emotion: "feel",
  wish: "feel",
  want: "feel",
  desire: "feel",
  need: "feel",

  // Existing / Being
  exist: "exist",
  live: "exist",
  survive: "exist",
  appear: "exist",
  occur: "exist",
  happen: "exist",
  emerge: "exist",
  become: "exist",

  // Fixing / Repairing
  fix: "fix",
  repair: "fix",
  restore: "fix",
  mend: "fix",
  correct: "fix",
  improve: "fix",
  update: "fix",

  // Holding / Preserving
  hold: "hold",
  keep: "hold",
  maintain: "hold",
  preserve: "hold",
  sustain: "hold",
  retain: "hold",
  store: "hold",
  save: "hold",

  // Connecting
  connect: "connect",
  link: "connect",
  attach: "connect",
  bind: "connect",
  associate: "connect",
  integrate: "connect",
  sync: "connect",

  // Seeing / Observing
  see: "see",
  look: "see",
  watch: "see",
  observe: "see",
  notice: "see",
  view: "see",
  detect: "see",
  find: "see",

  // Destroying
  destroy: "destroy",
  break: "destroy",
  damage: "destroy",
  demolish: "destroy",
  ruin: "destroy",
  eliminate: "destroy",
  remove: "destroy",
  delete: "destroy",

  // Social / Community
  social: "social",
  community: "social",
  society: "social",
  culture: "social",
  people: "social",
  person: "social",
  human: "social",
  individual: "social",

  // Possessing
  possess: "possess",
  own: "possess",
  property: "possess",
  asset: "possess",
  belonging: "possess",

  // Measure / Number
  measure: "size",
  number: "size",
  count: "size",
  amount: "size",
  quantity: "size",
  addition: "size",
  variety: "size",

  // Quality / State
  ability: "quality",
  capable: "quality",
  positive: "quality",
  negative: "quality",
  different: "quality",
  similar: "quality",
  same: "quality",
  difference: "quality",
  cold: "quality",
  warm: "quality",
  cool: "quality",

  // Food / Recipes
  food: "food",
  recipe: "food",
  cook: "food",
  cooking: "food",
  eat: "food",
  meal: "food",
  dish: "food",
  ingredient: "food",
  pasta: "food",
  chicken: "food",
  rice: "food",
  bread: "food",
  pizza: "food",
  soup: "food",
  salad: "food",
  dessert: "food",
  breakfast: "food",
  lunch: "food",
  dinner: "food",
  snack: "food",
  avocado: "food",
  egg: "food",
  cheese: "food",
  tomato: "food",
  sauce: "food",
  bake: "food",
  fry: "food",
  roast: "food",
  boil: "food",
  grill: "food",
  nutrition: "food",
  protein: "food",
  calorie: "food",
  calories: "food",
  diet: "food",
  vegan: "food",
  vegetarian: "food",
  cuisine: "food",
  restaurant: "food",
  kitchen: "food",
  tikka: "food",
  masala: "food",
  curry: "food",
  spice: "food",
  herb: "food",
  flavor: "food",
  taste: "food",
  menu: "food",
  dietary: "food",

  // Sport / Athletics
  game: "sport",
  match: "sport",
  score: "sport",
  goal: "sport",
  team: "sport",
  player: "sport",
  league: "sport",
  champion: "sport",
  tournament: "sport",
  season: "sport",
  fixture: "sport",
  result: "sport",
  standing: "sport",
  standings: "sport",
  athlete: "sport",
  coach: "sport",
  football: "sport",
  soccer: "sport",
  basketball: "sport",
  tennis: "sport",
  cricket: "sport",
  rugby: "sport",
  swimming: "sport",
  cycling: "sport",
  golf: "sport",
  formula: "sport",
  racing: "sport",
  championship: "sport",
  olympic: "sport",
  medal: "sport",
  referee: "sport",
  stadium: "sport",
  pitch: "sport",
  court: "sport",
  cup: "sport",
  squad: "sport",
  club: "sport",

  // Health (extended)
  symptom: "health",
  symptoms: "health",
  pain: "health",
  fever: "health",
  cough: "health",
  headache: "health",
  nausea: "health",
  fatigue: "health",
  dehydration: "health",
  vitamin: "health",
  dose: "health",
  ibuprofen: "health",
  medication: "health",
  pharmaceutical: "health",
  drug: "health",
  pharmacy: "health",
  hospital: "health",
  clinic: "health",
  doctor: "health",
  nurse: "health",
  patient: "health",
  therapy: "health",
  surgery: "health",
  diagnosis: "health",
  prescription: "health",
  antibiotic: "health",
  vaccine: "health",
  allergy: "health",
  infection: "health",
  injury: "health",
  appendicitis: "health",
  diabetes: "health",
  hypertension: "health",
  supplement: "health",
  wellbeing: "health",

  // Time / Calendar
  schedule: "time",
  reminder: "time",
  appointment: "time",
  calendar: "time",
  meeting: "time",
  deadline: "time",
  event: "time",
  booking: "time",
  slot: "time",
  block: "time",
  monday: "time",
  tuesday: "time",
  wednesday: "time",
  thursday: "time",
  friday: "time",
  saturday: "time",
  sunday: "time",
  today: "time",
  tomorrow: "time",
  yesterday: "time",
  morning: "time",
  afternoon: "time",
  evening: "time",
  night: "time",
  noon: "time",
  midnight: "time",
  week: "time",
  month: "time",
  year: "time",
  easter: "time",
  christmas: "time",
  holiday: "time",
  anniversary: "time",
  birthday: "time",
  date: "time",

  // Measure (extended)
  percent: "measure",
  percentage: "measure",
  kilometer: "measure",
  kilometres: "measure",
  miles: "measure",
  meter: "measure",
  kilogram: "measure",
  pounds: "measure",
  pound: "measure",
  celsius: "measure",
  fahrenheit: "measure",
  degrees: "measure",
  area: "measure",
  volume: "measure",
  weight: "measure",
  height: "measure",
  length: "measure",
  width: "measure",
  radius: "measure",
  diameter: "measure",
  circumference: "measure",
  square: "measure",
  rectangle: "measure",
  circle: "measure",
  triangle: "measure",
  calculate: "measure",
  calculation: "measure",
  convert: "measure",
  conversion: "measure",
  tip: "measure",
  total: "measure",
  sum: "measure",
  average: "measure",
  liter: "measure",
  gallon: "measure",
  acre: "measure",
  seconds: "measure",
  minutes: "measure",
  hours: "measure",

  // Place (extended)
  coffee: "place",
  cafe: "place",
  airport: "place",
  station: "place",
  hotel: "place",
  cinema: "place",
  park: "place",
  street: "place",
  location: "place",
  directions: "place",
  neighbourhood: "place",
  neighborhood: "place",
  district: "place",
  region: "place",
  city: "place",
  town: "place",
  village: "place",
  country: "place",
  map: "place",
  route: "place",
  distance: "place",
  italian: "place",
  chinese: "place",
  indian: "place",
  shops: "place",
  shopping: "place",
  mall: "place",
  supermarket: "place",
  emergency: "place",
  nearest: "place",
  nearby: "place",

  // Science (extended)
  dna: "science",
  replication: "science",
  mitosis: "science",
  meiosis: "science",
  fusion: "science",
  photosynthesis: "science",
  atom: "science",
  molecule: "science",
  cell: "science",
  evolution: "science",
  gravity: "science",
  chemical: "science",
  nucleus: "science",
  electron: "science",
  proton: "science",
  chromosome: "science",
  enzyme: "science",
  quantum: "science",
  entanglement: "science",
  element: "science",
  compound: "science",
  reaction: "science",
  energy: "science",
  force: "science",
  mass: "science",
  velocity: "science",
  acceleration: "science",
  photon: "science",
  radiation: "science",
  isotope: "science",
  carbon: "science",
  nitrogen: "science",
  oxygen: "science",
  light: "science",
  spectrum: "science",
  wavelength: "science",
  frequency: "science",
  magnetic: "science",
  electric: "science",
  voltage: "science",
  current: "science",
  resistance: "science",

  // Knowledge (extended)
  capital: "know",
  history: "know",
  encyclopedia: "know",
  population: "know",
  invented: "know",
  discovered: "know",
  founded: "know",
  fact: "know",
  definition: "know",
  meaning: "know",
  origin: "know",
  biography: "know",
  ancient: "know",
  medieval: "know",
  modern: "know",
  civilisation: "know",
  civilization: "know",
  empire: "know",
  philosophy: "know",
  philosopher: "know",
  language: "know",
  literature: "know",
  geography: "know",

  // Technology (extended)
  python: "tech",
  javascript: "tech",
  java: "tech",
  typescript: "tech",
  syntax: "tech",
  variable: "tech",
  database: "tech",
  sql: "tech",
  server: "tech",
  algorithm: "tech",
  script: "tech",
  terminal: "tech",
  cmd: "tech",
  import_stmt: "tech",
  error: "tech",
  bug: "tech",
  async: "tech",
  await: "tech",
  library: "write",
  framework: "tech",
  api: "tech",
  loop: "tech",
  array: "tech",
  string: "tech",
  integer: "tech",
  float: "tech",
  boolean: "tech",
  class: "tech",
  method: "tech",
  attribute: "tech",
  interface: "tech",
  debug: "tech",
  compile: "tech",
  deploy: "tech",
  container: "tech",
  cloud: "tech",
  network: "tech",
  security: "tech",
  encryption: "tech",
  hash: "tech",
  git: "tech",
  repository: "tech",
  branch: "tech",
  commit: "tech",
  pip: "tech",
  package: "tech",
  module: "tech",
  exception: "tech",
  null: "tech",
  pointer: "tech",
  segmentation: "tech",
  memory: "tech",
  cpu: "tech",
  gpu: "tech",
  hardware: "tech",

  // Finance / Trade (extended)
  stock: "trade",
  exchange: "trade",
  rate: "trade",
  gold: "trade",
  currency: "trade",
  bitcoin: "trade",
  crypto: "trade",
  cryptocurrency: "trade",
  nasdaq: "trade",
  investment: "trade",
  portfolio: "trade",
  dividend: "trade",
  profit: "trade",
  loss: "trade",
  revenue: "trade",
  inflation: "trade",
  interest: "trade",
  mortgage: "trade",
  loan: "trade",
  tax: "trade",
  budget: "trade",
  financial: "trade",
  fund: "trade",
  liability: "trade",
  eur: "trade",
  usd: "trade",
  gbp: "trade",

  // Messaging
  notify: "send",
  notification: "send",
  alert: "send",
  message: "send",
  ping: "send",
  text: "send",
  sms: "send",
  contact: "send",
  cc: "send",
  bcc: "send",
  reply: "send",
  inbox: "send",
  outbox: "send",

  // Weather (extended)
  forecast: "weather",
  temperature: "weather",
  rain: "weather",
  snow: "weather",
  storm: "weather",
  wind: "weather",
  cloudy: "weather",
  sunny: "weather",
  humid: "weather",
  humidity: "weather",
  precipitation: "weather",
  thunder: "weather",
  lightning: "weather",
  tornado: "weather",
  hurricane: "weather",
  fog: "weather",
  frost: "weather",
  ice: "weather",
  heatwave: "weather",

  // Color
  red: "color",
  blue: "color",
  green: "color",
  yellow: "color",
  black: "color",
  white: "color",
  orange: "color",
  purple: "color",
  pink: "color",
  brown: "color",
  grey: "color",
  gray: "color",
  golden: "color",
  cyan: "color",
  violet: "color",
  turquoise: "color",
  indigo: "color",
  beige: "color",

  // Material
  wood: "material",
  wooden: "material",
  metal: "material",
  iron: "material",
  steel: "material",
  glass: "material",
  stone: "material",
  plastic: "material",
  fabric: "material",
  cotton: "material",
  silk: "material",
  leather: "material",
  rubber: "material",
  ceramic: "material",
  concrete: "material",
  copper: "material",
  aluminum: "material",
  aluminium: "material",
  clay: "material",
  crystal: "material",
  silver: "material",

  // Animal
  dog: "animal",
  cat: "animal",
  bird: "animal",
  fish: "animal",
  horse: "animal",
  lion: "animal",
  tiger: "animal",
  elephant: "animal",
  bear: "animal",
  wolf: "animal",
  rabbit: "animal",
  snake: "animal",
  whale: "animal",
  dolphin: "animal",
  eagle: "animal",
  shark: "animal",
  monkey: "animal",
  gorilla: "animal",
  deer: "animal",
  fox: "animal",
  owl: "animal",
  parrot: "animal",
  penguin: "animal",
  crocodile: "animal",
  turtle: "animal",
  insect: "animal",
  butterfly: "animal",
  bee: "animal",
  ant: "animal",
  spider: "animal",
  frog: "animal",
  bat: "animal",
  rat: "animal",
  cow: "animal",
  sheep: "animal",
  goat: "animal",
  camel: "animal",
  giraffe: "animal",
  zebra: "animal",
  rhino: "animal",
  octopus: "animal",
  jellyfish: "animal",

  // Plant
  tree: "plant",
  flower: "plant",
  grass: "plant",
  rose: "plant",
  oak: "plant",
  pine: "plant",
  bush: "plant",
  vine: "plant",
  seed: "plant",
  root: "plant",
  leaf: "plant",
  leaves: "plant",
  cactus: "plant",
  moss: "plant",
  fern: "plant",
  bamboo: "plant",
  mushroom: "plant",
  algae: "plant",
  seaweed: "plant",
  petal: "plant",
  pollen: "plant",
  blossom: "plant",

  // Nature / Environment
  nature: "nature",
  environment: "nature",
  ecosystem: "nature",
  ocean: "nature",
  sea: "nature",
  lake: "nature",
  river: "nature",
  mountain: "nature",
  desert: "nature",
  forest: "nature",
  jungle: "nature",
  island: "nature",
  volcano: "nature",
  valley: "nature",
  canyon: "nature",
  habitat: "nature",
  wildlife: "nature",
  landscape: "nature",
  coast: "nature",
  beach: "nature",
  cliff: "nature",
  glacier: "nature",
  reef: "nature",
  swamp: "nature",
  wetland: "nature",
  atmosphere: "nature",
  soil: "nature",

  // Body / Anatomy
  arm: "body",
  leg: "body",
  hand: "body",
  foot: "body",
  feet: "body",
  head: "body",
  neck: "body",
  chest: "body",
  back: "body",
  shoulder: "body",
  knee: "body",
  elbow: "body",
  hip: "body",
  heart: "body",
  brain: "body",
  liver: "body",
  kidney: "body",
  lung: "body",
  lungs: "body",
  stomach: "body",
  bone: "body",
  muscle: "body",
  skin: "body",
  blood: "body",
  nerve: "body",
  eye: "body",
  ear: "body",
  nose: "body",
  mouth: "body",
  throat: "body",
  spine: "body",
  rib: "body",
  vein: "body",
  artery: "body",
  organ: "body",
  tissue: "body",
  joint: "body",

  // Art / Creative culture
  painting: "art",
  drawing: "art",
  sculpture: "art",
  photography: "art",
  photograph: "art",
  film: "art",
  movie: "art",
  gallery: "art",
  museum: "art",
  exhibition: "art",
  theater: "art",
  theatre: "art",
  dance: "art",
  ballet: "art",
  opera: "art",
  orchestra: "art",
  artwork: "art",
  illustration: "art",
  portrait: "art",
  animation: "art",
  comic: "art",
  novel: "art",
  poem: "art",
  lyrics: "art",
  album: "art",
  instrument: "art",
  guitar: "art",
  piano: "art",
  violin: "art",
  song: "art",
  artist: "art",
  musician: "art",
  painter: "art",
  actor: "art",
  actress: "art",
  director: "art",
  photographer: "art",
  music: "art",
  melody: "art",
  rhythm: "art",
  // ─── CST vocabulary import ──────────────────────────────────────────────────

  // Take / Receive / Acquire (new field)
  capture: "take",
  seize: "take",
  snatch: "take",
  steal: "take",
  take: "take",

  // Change / Transform (new field)
  adapt: "change",
  adjust: "change",
  alter: "change",
  change: "change",
  decline: "change",
  decrease: "change",
  evolve: "change",
  increase: "change",
  lower: "change",
  modify: "change",
  raise: "change",
  recovery: "change",
  reduce: "change",
  reform: "change",
  replace: "change",
  shift: "change",
  shrink: "change",
  switch: "change",
  transform: "change",
  vary: "change",

  // Social / Person (extended)
  accountant: "social",
  activist: "social",
  admiral: "social",
  adolescent: "social",
  adult: "social",
  advisor: "social",
  advocate: "social",
  agnostic: "social",
  agreement: "social",
  alliance: "social",
  ally: "social",
  analyst: "social",
  ancestor: "social",
  announcer: "social",
  apprentice: "social",
  architect: "social",
  artisan: "social",
  assassin: "social",
  association: "social",
  asylum: "social",
  atheist: "social",
  attorney: "social",
  audience: "social",
  aunt: "social",
  baby: "social",
  banker: "social",
  believer: "social",
  bilateral: "social",
  bishop: "social",
  board: "social",
  boy: "social",
  bride: "social",
  broker: "social",
  brother: "social",
  captain: "social",
  challenge: "social",
  charity: "social",
  chief: "social",
  child: "social",
  children: "social",
  cleric: "social",
  client: "social",
  coalition: "social",
  colleague: "social",
  colonel: "social",
  comedian: "social",
  commander: "social",
  commentator: "social",
  companion: "social",
  composer: "social",
  conductor: "social",
  consultant: "social",
  controversy: "social",
  cooperate: "social",
  correspondent: "social",
  couple: "social",
  cousin: "social",
  craftsman: "social",
  crowd: "social",
  customer: "social",
  daughter: "social",
  dealer: "social",
  defendant: "social",
  demonstration: "social",
  descendant: "social",
  designer: "social",
  devotee: "social",
  disciple: "social",
  discrimination: "social",
  diverse: "social",
  domestic: "social",
  dr: "social",
  drummer: "social",
  duke: "social",
  editor: "social",
  elder: "social",
  emancipation: "social",
  emigration: "social",
  emperor: "social",
  empress: "social",
  enemy: "social",
  engineer: "social",
  entertainer: "social",
  entrepreneur: "social",
  equality: "social",
  equity: "social",
  ethnic: "social",
  expert: "social",
  exploitation: "social",
  explorer: "social",
  family: "social",
  father: "social",
  female: "social",
  filmmaker: "social",
  follower: "social",
  foreign: "social",
  founder: "social",
  friend: "social",
  gender: "social",
  generation: "social",
  girl: "social",
  global: "social",
  grandfather: "social",
  grandmother: "social",
  groom: "social",
  guest: "social",
  guitarist: "social",
  guru: "social",
  heir: "social",
  hero: "social",
  hierarchy: "social",
  homeless: "social",
  hospitality: "social",
  host: "social",
  household: "social",
  husband: "social",
  imam: "social",
  immigrant: "social",
  immigration: "social",
  inclusive: "social",
  inequality: "social",
  infant: "social",
  inhabitant: "social",
  institutional: "social",
  international: "social",
  investor: "social",
  john: "social",
  junior: "social",
  king: "social",
  knight: "social",
  lawyer: "social",
  leader: "social",
  lieutenant: "social",
  local: "social",
  lord: "social",
  lover: "social",
  majority: "social",
  male: "social",
  man: "social",
  manufacturer: "social",
  marriage: "social",
  married: "social",
  martyr: "social",
  master: "social",
  mate: "social",
  member: "social",
  mentor: "social",
  merchant: "social",
  minority: "social",
  missionary: "social",
  monarch: "social",
  monk: "social",
  mother: "social",
  multilateral: "social",
  native: "social",
  navigator: "social",
  negotiation: "social",
  neighbor: "social",
  nephew: "social",
  niece: "social",
  noble: "social",
  novice: "social",
  nun: "social",
  observer: "social",
  officer: "social",
  opponent: "social",
  oppression: "social",
  organization: "social",
  organizational: "social",
  orphan: "social",
  panel: "social",
  parent: "social",
  participant: "social",
  partner: "social",
  partnership: "social",
  party: "social",
  passenger: "social",
  performer: "social",
  persecution: "social",
  personal: "social",
  philanthropy: "social",
  pianist: "social",
  pilgrim: "social",
  pilot: "social",
  pioneer: "social",
  plaintiff: "social",
  playwright: "social",
  pope: "social",
  poverty: "social",
  presenter: "social",
  president: "social",
  prestige: "social",
  priest: "social",
  prince: "social",
  princess: "social",
  privilege: "social",
  producer: "social",
  prophet: "social",
  prosecutor: "social",
  protest: "social",
  publisher: "social",
  queen: "social",
  rabbi: "social",
  race: "social",
  racial: "social",
  rebellion: "social",
  refugee: "social",
  reporter: "social",
  reputation: "social",
  researcher: "social",
  resident: "social",
  respect: "social",
  riot: "social",
  rival: "social",
  ruler: "social",
  saint: "social",
  scandal: "social",
  scientist: "social",
  sculptor: "social",
  segregation: "social",
  self: "social",
  senior: "social",
  sergeant: "social",
  sexual: "social",
  sibling: "social",
  sister: "social",
  skeptic: "social",
  slavery: "social",
  soldier: "social",
  solidarity: "social",
  son: "social",
  spectator: "social",
  spouse: "social",
  spy: "social",
  status: "social",
  stranger: "social",
  suffrage: "social",
  suitor: "social",
  summit: "social",
  supplier: "social",
  supporter: "social",
  teenager: "social",
  toddler: "social",
  tourist: "social",
  trader: "social",
  traveler: "social",
  umpire: "social",
  uncle: "social",
  union: "social",
  uprising: "social",
  veteran: "social",
  victim: "social",
  visitor: "social",
  vocalist: "social",
  volunteer: "social",
  warrior: "social",
  welfare: "social",
  widow: "social",
  widower: "social",
  wife: "social",
  woman: "social",
  worker: "social",
  youth: "social",

  // Place (extended)
  adjacent: "place",
  africa: "place",
  african: "place",
  alps: "place",
  amazon: "place",
  america: "place",
  american: "place",
  angeles: "place",
  antarctic: "place",
  aquatic: "place",
  arab: "place",
  arctic: "place",
  asia: "place",
  asian: "place",
  atlantic: "place",
  australia: "place",
  australian: "place",
  bay: "place",
  beijing: "place",
  berlin: "place",
  border: "place",
  boundary: "place",
  brazil: "place",
  bridge: "place",
  british: "place",
  california: "place",
  canada: "place",
  canadian: "place",
  caribbean: "place",
  central: "place",
  chicago: "place",
  china: "place",
  coastal: "place",
  continent: "place",
  continental: "place",
  county: "place",
  destination: "place",
  distant: "place",
  domain: "place",
  dutch: "place",
  east: "place",
  egypt: "place",
  england: "place",
  english: "place",
  eu: "place",
  europe: "place",
  european: "place",
  field: "place",
  florida: "place",
  france: "place",
  francisco: "place",
  french: "place",
  frontier: "place",
  garden: "place",
  german: "place",
  germany: "place",
  globe: "place",
  greek: "place",
  ground: "place",
  harbor: "place",
  hill: "place",
  himalaya: "place",
  india: "place",
  indigenous: "place",
  indonesia: "place",
  iran: "place",
  iraq: "place",
  ireland: "place",
  irish: "place",
  israel: "place",
  italy: "place",
  japan: "place",
  japanese: "place",
  jewish: "place",
  kenya: "place",
  kong: "place",
  korea: "place",
  land: "place",
  left: "place",
  locate: "place",
  london: "place",
  los: "place",
  maritime: "place",
  mediterranean: "place",
  mexican: "place",
  mexico: "place",
  mile: "place",
  mississippi: "place",
  moscow: "place",
  nigeria: "place",
  nile: "place",
  north: "place",
  pacific: "place",
  pakistan: "place",
  paris: "place",
  path: "place",
  peninsula: "place",
  persian: "place",
  philippines: "place",
  plain: "place",
  port: "place",
  position: "place",
  province: "place",
  realm: "place",
  regional: "place",
  remote: "place",
  resort: "place",
  right: "place",
  road: "place",
  roman: "place",
  rome: "place",
  rural: "place",
  russia: "place",
  russian: "place",
  sahara: "place",
  san: "place",
  scotland: "place",
  scottish: "place",
  settlement: "place",
  singapore: "place",
  site: "place",
  south: "place",
  spain: "place",
  spanish: "place",
  surface: "place",
  swedish: "place",
  terrestrial: "place",
  territory: "place",
  texas: "place",
  thailand: "place",
  tokyo: "place",
  tropical: "place",
  turkey: "place",
  uk: "place",
  urban: "place",
  us: "place",
  vietnam: "place",
  wales: "place",
  washington: "place",
  west: "place",
  western: "place",
  world: "place",
  worldwide: "place",
  york: "place",
  zone: "place",

  // Govern / Politics (extended)
  accountability: "govern",
  administration: "govern",
  administrative: "govern",
  agency: "govern",
  ambassador: "govern",
  amendment: "govern",
  ammunition: "govern",
  armed: "govern",
  armistice: "govern",
  armor: "govern",
  army: "govern",
  arrest: "govern",
  assassination: "govern",
  authority: "govern",
  autonomous: "govern",
  bail: "govern",
  ban: "govern",
  battlefield: "govern",
  bureau: "govern",
  campaign: "govern",
  ceasefire: "govern",
  censorship: "govern",
  citizen: "govern",
  civil: "govern",
  colonial: "govern",
  colony: "govern",
  commission: "govern",
  committee: "govern",
  commonwealth: "govern",
  communist: "govern",
  confederation: "govern",
  congress: "govern",
  conservative: "govern",
  constitution: "govern",
  constitutional: "govern",
  consul: "govern",
  conviction: "govern",
  corruption: "govern",
  council: "govern",
  coup: "govern",
  crime: "govern",
  criminal: "govern",
  custody: "govern",
  decision: "govern",
  decree: "govern",
  delegate: "govern",
  democracy: "govern",
  democratic: "govern",
  department: "govern",
  detention: "govern",
  diplomacy: "govern",
  dynasty: "govern",
  election: "govern",
  embassy: "govern",
  enforcement: "govern",
  envoy: "govern",
  espionage: "govern",
  executive: "govern",
  explosive: "govern",
  extremist: "govern",
  federal: "govern",
  federation: "govern",
  fraud: "govern",
  freedom: "govern",
  genocide: "govern",
  governance: "govern",
  government: "govern",
  governor: "govern",
  hearing: "govern",
  imperial: "govern",
  independence: "govern",
  invasion: "govern",
  judicial: "govern",
  jury: "govern",
  justice: "govern",
  kingdom: "govern",
  law: "govern",
  leadership: "govern",
  legal: "govern",
  legislation: "govern",
  legislative: "govern",
  legitimacy: "govern",
  liberal: "govern",
  liberation: "govern",
  liberty: "govern",
  mandate: "govern",
  massacre: "govern",
  mayor: "govern",
  minister: "govern",
  ministry: "govern",
  missile: "govern",
  mission: "govern",
  nation: "govern",
  national: "govern",
  nationalization: "govern",
  naval: "govern",
  occupation: "govern",
  official: "govern",
  ordinance: "govern",
  parliament: "govern",
  parole: "govern",
  peace: "govern",
  penalty: "govern",
  police: "govern",
  policy: "govern",
  political: "govern",
  politics: "govern",
  prison: "govern",
  private: "govern",
  progressive: "govern",
  prosecution: "govern",
  public: "govern",
  punishment: "govern",
  radical: "govern",
  regime: "govern",
  regulation: "govern",
  republic: "govern",
  republican: "govern",
  revolution: "govern",
  revolutionary: "govern",
  royal: "govern",
  sanction: "govern",
  senate: "govern",
  sentence: "govern",
  shield: "govern",
  socialist: "govern",
  sovereign: "govern",
  sovereignty: "govern",
  statute: "govern",
  supervise: "govern",
  surrender: "govern",
  surveillance: "govern",
  transparency: "govern",
  treaty: "govern",
  trial: "govern",
  tribunal: "govern",
  united: "govern",
  weapon: "govern",

  // Quality / State (extended)
  able: "quality",
  accurate: "quality",
  advanced: "quality",
  alternative: "quality",
  apparent: "quality",
  appropriate: "quality",
  available: "quality",
  bad: "quality",
  basic: "quality",
  beautiful: "quality",
  benchmark: "quality",
  best: "quality",
  better: "quality",
  bright: "quality",
  certain: "quality",
  characteristic: "quality",
  clean: "quality",
  clear: "quality",
  common: "quality",
  complex: "quality",
  consistent: "quality",
  conventional: "quality",
  criterion: "quality",
  critical: "quality",
  danger: "quality",
  dangerous: "quality",
  dark: "quality",
  difficult: "quality",
  dignity: "quality",
  dirty: "quality",
  distinct: "quality",
  dominant: "quality",
  dry: "quality",
  easy: "quality",
  effective: "quality",
  efficiency: "quality",
  efficient: "quality",
  equal: "quality",
  essential: "quality",
  exact: "quality",
  exclusive: "quality",
  extraordinary: "quality",
  extreme: "quality",
  false: "quality",
  famous: "quality",
  final: "quality",
  free: "quality",
  fundamental: "quality",
  general: "quality",
  generosity: "quality",
  genius: "quality",
  good: "quality",
  hard: "quality",
  honor: "quality",
  hot: "quality",
  important: "quality",
  impossible: "quality",
  independent: "quality",
  initial: "quality",
  integrity: "quality",
  intense: "quality",
  intensive: "quality",
  key: "quality",
  known: "quality",
  likely: "quality",
  main: "quality",
  manner: "quality",
  mild: "quality",
  moderate: "quality",
  natural: "quality",
  necessary: "quality",
  normal: "quality",
  obvious: "quality",
  opposite: "quality",
  ordinary: "quality",
  parallel: "quality",
  particular: "quality",
  poor: "quality",
  popular: "quality",
  possible: "quality",
  potential: "quality",
  precise: "quality",
  primary: "quality",
  primitive: "quality",
  prominent: "quality",
  proper: "quality",
  rare: "quality",
  real: "quality",
  relevant: "quality",
  remarkable: "quality",
  resistant: "quality",
  rich: "quality",
  risk: "quality",
  safe: "quality",
  secondary: "quality",
  sensitive: "quality",
  severe: "quality",
  simple: "quality",
  soft: "quality",
  sophisticated: "quality",
  special: "quality",
  specific: "quality",
  stable: "quality",
  standard: "quality",
  strong: "quality",
  subtle: "quality",
  successful: "quality",
  suitable: "quality",
  talent: "quality",
  threat: "quality",
  true: "quality",
  typical: "quality",
  ugly: "quality",
  unique: "quality",
  unknown: "quality",
  unlikely: "quality",
  virtue: "quality",
  visible: "quality",
  vital: "quality",
  vulnerable: "quality",
  weak: "quality",
  wet: "quality",
  worst: "quality",

  // Technology (extended)
  acoustic: "tech",
  adapter: "tech",
  antenna: "tech",
  app: "tech",
  apparatus: "tech",
  application: "tech",
  artificial: "tech",
  automate: "tech",
  automatic: "tech",
  backup: "tech",
  bandwidth: "tech",
  battery: "tech",
  browser: "tech",
  buffer: "tech",
  cable: "tech",
  cache: "tech",
  camera: "tech",
  chip: "tech",
  circuit: "tech",
  compress: "tech",
  connector: "tech",
  decode: "tech",
  device: "tech",
  disk: "tech",
  download: "tech",
  drone: "tech",
  electrical: "tech",
  electronic: "tech",
  encrypt: "tech",
  engine: "tech",
  fiber: "tech",
  file: "tech",
  filter: "tech",
  format: "tech",
  frame: "tech",
  fuel: "tech",
  gps: "tech",
  homepage: "tech",
  implementation: "tech",
  infrared: "tech",
  innovation: "tech",
  install: "tech",
  internet: "tech",
  keyboard: "tech",
  laser: "tech",
  latency: "tech",
  login: "tech",
  machine: "tech",
  mechanical: "tech",
  mechanism: "tech",
  microwave: "tech",
  modem: "tech",
  motor: "tech",
  navigation: "tech",
  nuclear: "tech",
  optical: "tech",
  optimization: "tech",
  packet: "tech",
  password: "tech",
  payload: "tech",
  phone: "tech",
  pixel: "tech",
  platform: "tech",
  power: "tech",
  printer: "tech",
  process: "tech",
  processor: "tech",
  protocol: "tech",
  proxy: "tech",
  radar: "tech",
  radio: "tech",
  receiver: "tech",
  render: "tech",
  resolution: "tech",
  robot: "tech",
  rocket: "tech",
  router: "tech",
  satellite: "tech",
  scanner: "tech",
  screen: "tech",
  sensor: "tech",
  simulation: "tech",
  socket: "tech",
  solar: "tech",
  sonar: "tech",
  spacecraft: "tech",
  storage: "tech",
  stream: "tech",
  technical: "tech",
  technology: "tech",
  telephone: "tech",
  television: "tech",
  throughput: "tech",
  tool: "tech",
  track: "tech",
  transmitter: "tech",
  ultrasound: "tech",
  upgrade: "tech",
  upload: "tech",
  user: "tech",
  web: "tech",
  website: "tech",
  wire: "tech",

  // Knowledge / Learning (extended)
  academic: "know",
  accreditation: "know",
  beginning: "know",
  bottom: "know",
  census: "know",
  center: "know",
  certification: "know",
  character: "know",
  college: "know",
  corner: "know",
  course: "know",
  curriculum: "know",
  degree: "know",
  demonstrate: "know",
  diploma: "know",
  discipline: "know",
  dissertation: "know",
  edge: "know",
  education: "know",
  educational: "know",
  enrollment: "know",
  exam: "know",
  examination: "know",
  experience: "know",
  explore: "know",
  figure: "know",
  front: "know",
  graduate: "know",
  graduation: "know",
  hear: "know",
  historian: "know",
  historical: "know",
  illustrate: "know",
  image: "know",
  inquiry: "know",
  institute: "know",
  institution: "know",
  intellectual: "know",
  interview: "know",
  investigate: "know",
  investigation: "know",
  knowledge: "know",
  label: "know",
  lecture: "know",
  lesson: "know",
  line: "know",
  linguistic: "know",
  listen: "know",
  literary: "know",
  mark: "know",
  math: "know",
  mathematical: "know",
  mathematics: "know",
  mean: "know",
  measurement: "know",
  middle: "know",
  observation: "know",
  phrase: "know",
  picture: "know",
  point: "know",
  poll: "know",
  practical: "know",
  practice: "know",
  prediction: "know",
  professor: "know",
  pupil: "know",
  qualification: "know",
  scholarship: "know",
  school: "know",
  search: "know",
  sense: "know",
  shape: "know",
  side: "know",
  sight: "know",
  sign: "know",
  skill: "know",
  statistic: "know",
  subject: "know",
  symbol: "know",
  teacher: "know",
  term: "know",
  theoretical: "know",
  thesis: "know",
  top: "know",
  train: "know",
  training: "know",
  tuition: "know",
  university: "know",
  word: "know",

  // Size / Quantity (extended)
  absolute: "size",
  additional: "size",
  big: "size",
  billion: "size",
  capacity: "size",
  comprehensive: "size",
  considerable: "size",
  deep: "size",
  dimension: "size",
  double: "size",
  dozen: "size",
  eight: "size",
  empty: "size",
  enormous: "size",
  entire: "size",
  extensive: "size",
  extent: "size",
  fifth: "size",
  first: "size",
  five: "size",
  four: "size",
  fourth: "size",
  fraction: "size",
  full: "size",
  gap: "size",
  great: "size",
  half: "size",
  heavy: "size",
  high: "size",
  huge: "size",
  hundred: "size",
  interval: "size",
  large: "size",
  last: "size",
  level: "size",
  limit: "size",
  little: "size",
  long: "size",
  low: "size",
  magnitude: "size",
  major: "size",
  margin: "size",
  massive: "size",
  maximum: "size",
  million: "size",
  minimum: "size",
  minor: "size",
  multiple: "size",
  narrow: "size",
  nine: "size",
  one: "size",
  overall: "size",
  pair: "size",
  portion: "size",
  proportion: "size",
  range: "size",
  ratio: "size",
  relative: "size",
  remainder: "size",
  scale: "size",
  scope: "size",
  segment: "size",
  seven: "size",
  short: "size",
  significant: "size",
  single: "size",
  six: "size",
  small: "size",
  space: "size",
  span: "size",
  substantial: "size",
  surplus: "size",
  tall: "size",
  ten: "size",
  thick: "size",
  thin: "size",
  third: "size",
  thousand: "size",
  three: "size",
  threshold: "size",
  tiny: "size",
  triple: "size",
  two: "size",
  various: "size",
  vast: "size",
  whole: "size",
  wide: "size",
  widespread: "size",

  // Trade / Finance (extended)
  acquisition: "trade",
  agricultural: "trade",
  agriculture: "trade",
  allowance: "trade",
  audit: "trade",
  bank: "trade",
  bargain: "trade",
  benefit: "trade",
  bond: "trade",
  bonus: "trade",
  boom: "trade",
  bust: "trade",
  capitalist: "trade",
  career: "trade",
  coal: "trade",
  commercial: "trade",
  commodity: "trade",
  company: "trade",
  compensation: "trade",
  competitive: "trade",
  compliance: "trade",
  consumer: "trade",
  contract: "trade",
  copyright: "trade",
  corporation: "trade",
  credit: "trade",
  crisis: "trade",
  crop: "trade",
  debt: "trade",
  deduction: "trade",
  deficit: "trade",
  donation: "trade",
  earn: "trade",
  economic: "trade",
  embargo: "trade",
  employment: "trade",
  estate: "trade",
  exemption: "trade",
  export: "trade",
  farm: "trade",
  finance: "trade",
  goods: "trade",
  growth: "trade",
  harvest: "trade",
  import: "trade",
  impoverished: "trade",
  income: "trade",
  industrial: "trade",
  industry: "trade",
  insurance: "trade",
  invest: "trade",
  job: "trade",
  license: "trade",
  merger: "trade",
  mine: "trade",
  money: "trade",
  negotiate: "trade",
  oil: "trade",
  opportunity: "trade",
  patent: "trade",
  pay: "trade",
  pension: "trade",
  plantation: "trade",
  privatization: "trade",
  product: "trade",
  productive: "trade",
  professional: "trade",
  profitable: "trade",
  prosperous: "trade",
  purchase: "trade",
  quota: "trade",
  recession: "trade",
  resource: "trade",
  retirement: "trade",
  salary: "trade",
  sector: "trade",
  service: "trade",
  spend: "trade",
  subsidy: "trade",
  tariff: "trade",
  timber: "trade",
  trademark: "trade",
  transaction: "trade",
  unemployment: "trade",
  value: "trade",
  wage: "trade",
  wealth: "trade",
  wealthy: "trade",

  // Think / Reason (extended)
  accept: "think",
  advise: "think",
  agree: "think",
  analysis: "think",
  approve: "think",
  argument: "think",
  assessment: "think",
  assume: "think",
  attention: "think",
  attitude: "think",
  awareness: "think",
  blame: "think",
  claim: "think",
  cognition: "think",
  commentary: "think",
  concept: "think",
  concern: "think",
  conclusion: "think",
  confirm: "think",
  consciousness: "think",
  considered: "think",
  critic: "think",
  criticize: "think",
  debate: "think",
  deny: "think",
  disagree: "think",
  discussion: "think",
  doctrine: "think",
  doubt: "think",
  elect: "think",
  estimate: "think",
  evaluation: "think",
  focus: "think",
  forget: "think",
  idea: "think",
  ideology: "think",
  imagination: "think",
  imagine: "think",
  inspection: "think",
  intelligence: "think",
  interpretation: "think",
  issue: "think",
  judgment: "think",
  mind: "think",
  notion: "think",
  opinion: "think",
  opt: "think",
  perception: "think",
  perspective: "think",
  philosophical: "think",
  pick: "think",
  ponder: "think",
  praise: "think",
  prefer: "think",
  principle: "think",
  problem: "think",
  propose: "think",
  psychological: "think",
  question: "think",
  recall: "think",
  recommend: "think",
  reflect: "think",
  reject: "think",
  remind: "think",
  resolve: "think",
  response: "think",
  review: "think",
  select: "think",
  solution: "think",
  soul: "think",
  speculate: "think",
  spirit: "think",
  strategy: "think",
  suggest: "think",
  suppose: "think",
  suspect: "think",
  tactic: "think",
  thought: "think",
  vote: "think",
  warn: "think",
  wisdom: "think",
  wonder: "think",

  // Move / Travel (extended)
  action: "move",
  activity: "move",
  advance: "move",
  adventure: "move",
  aerial: "move",
  aircraft: "move",
  airplane: "move",
  approach: "move",
  boat: "move",
  bus: "move",
  car: "move",
  climb: "move",
  commute: "move",
  continue: "move",
  cross: "move",
  direction: "move",
  enter: "move",
  escape: "move",
  exit: "move",
  expand: "move",
  expedition: "move",
  exploration: "move",
  extend: "move",
  fall: "move",
  fast: "move",
  flight: "move",
  flow: "move",
  fly: "move",
  follow: "move",
  guide: "move",
  journey: "move",
  jump: "move",
  maneuver: "move",
  migrate: "move",
  migration: "move",
  passage: "move",
  pilgrimage: "move",
  pour: "move",
  proceed: "move",
  pursue: "move",
  quest: "move",
  rail: "move",
  reach: "move",
  retreat: "move",
  return: "move",
  rise: "move",
  roll: "move",
  sail: "move",
  scatter: "move",
  shake: "move",
  sink: "move",
  slide: "move",
  slow: "move",
  speed: "move",
  spill: "move",
  spin: "move",
  spread: "move",
  step: "move",
  swing: "move",
  tourism: "move",
  transportation: "move",
  truck: "move",
  turn: "move",
  vehicle: "move",
  voyage: "move",
  wander: "move",
  way: "move",

  // Time (extended)
  ago: "time",
  already: "time",
  always: "time",
  annual: "time",
  arrange: "time",
  autumn: "time",
  begin: "time",
  century: "time",
  chronic: "time",
  complete: "time",
  contemporary: "time",
  daily: "time",
  day: "time",
  decade: "time",
  delay: "time",
  early: "time",
  end: "time",
  era: "time",
  eventually: "time",
  finish: "time",
  forever: "time",
  future: "time",
  hour: "time",
  hurry: "time",
  just: "time",
  late: "time",
  minute: "time",
  new: "time",
  next: "time",
  often: "time",
  old: "time",
  original: "time",
  past: "time",
  period: "time",
  permanent: "time",
  phase: "time",
  plan: "time",
  postpone: "time",
  present: "time",
  previous: "time",
  prior: "time",
  recent: "time",
  reserve: "time",
  rush: "time",
  second: "time",
  sometimes: "time",
  soon: "time",
  spring: "time",
  stage: "time",
  start: "time",
  still: "time",
  subsequent: "time",
  summer: "time",
  temporary: "time",
  usually: "time",
  wait: "time",
  winter: "time",
  young: "time",

  // Hold / Contain (extended)
  access: "hold",
  act: "hold",
  apply: "hold",
  aspect: "hold",
  base: "hold",
  basis: "hold",
  belong: "hold",
  bit: "hold",
  bury: "hold",
  category: "hold",
  classify: "hold",
  component: "hold",
  comprise: "hold",
  conceal: "hold",
  consist: "hold",
  contain: "hold",
  cover: "hold",
  define: "hold",
  depend: "hold",
  disguise: "hold",
  division: "hold",
  employ: "hold",
  equipment: "hold",
  expose: "hold",
  feature: "hold",
  foundation: "hold",
  hide: "hold",
  identify: "hold",
  include: "hold",
  indicate: "hold",
  involve: "hold",
  kind: "hold",
  list: "hold",
  mask: "hold",
  model: "hold",
  part: "hold",
  pattern: "hold",
  piece: "hold",
  purpose: "hold",
  refer: "hold",
  relate: "hold",
  represent: "hold",
  reveal: "hold",
  role: "hold",
  section: "hold",
  sequence: "hold",
  series: "hold",
  set: "hold",
  sort: "hold",
  source: "hold",
  uncover: "hold",
  unit: "hold",
  usage: "hold",
  use: "hold",
  used: "hold",
  using: "hold",
  utilize: "hold",
  version: "hold",

  // Health / Medicine (extended)
  acute: "health",
  alcohol: "health",
  ankle: "health",
  asthma: "health",
  bacteria: "health",
  birth: "health",
  bleeding: "health",
  breathe: "health",
  caffeine: "health",
  cancer: "health",
  consume: "health",
  consumption: "health",
  death: "health",
  disorder: "health",
  dosage: "health",
  exercise: "health",
  finger: "health",
  fit: "health",
  fracture: "health",
  hair: "health",
  healthy: "health",
  hormone: "health",
  illness: "health",
  inflammation: "health",
  intestine: "health",
  jaw: "health",
  limb: "health",
  lip: "health",
  medical: "health",
  mental: "health",
  nail: "health",
  nutrient: "health",
  obesity: "health",
  pregnancy: "health",
  prognosis: "health",
  rehabilitation: "health",
  sick: "health",
  skull: "health",
  smell: "health",
  stroke: "health",
  swelling: "health",
  syndrome: "health",
  toe: "health",
  tongue: "health",
  tooth: "health",
  trauma: "health",
  treatment: "health",
  tumor: "health",
  vessel: "health",
  virus: "health",
  waist: "health",
  wound: "health",
  wrist: "health",

  // Science / Research (extended)
  acid: "science",
  adaptation: "science",
  atmospheric: "science",
  biodiversity: "science",
  biological: "science",
  climate: "science",
  coefficient: "science",
  concentration: "science",
  conservation: "science",
  correlation: "science",
  cosmic: "science",
  density: "science",
  ecology: "science",
  emission: "science",
  environmental: "science",
  equation: "science",
  evidence: "science",
  experimental: "science",
  extinction: "science",
  fossil: "science",
  gas: "science",
  gene: "science",
  genetic: "science",
  geological: "science",
  hypothesis: "science",
  laboratory: "science",
  liquid: "science",
  lunar: "science",
  mineral: "science",
  momentum: "science",
  mutation: "science",
  orbit: "science",
  organic: "science",
  organism: "science",
  parameter: "science",
  phenomenon: "science",
  physical: "science",
  pollution: "science",
  proof: "science",
  prove: "science",
  renewable: "science",
  scientific: "science",
  seismic: "science",
  solid: "science",
  species: "science",
  substance: "science",
  sustainable: "science",
  synthetic: "science",
  test: "science",
  theorem: "science",
  volcanic: "science",

  // Exist / Dwell (extended)
  age: "exist",
  alive: "exist",
  apartment: "exist",
  arise: "exist",
  born: "exist",
  building: "exist",
  case: "exist",
  cause: "exist",
  church: "exist",
  circumstance: "exist",
  condition: "exist",
  consequence: "exist",
  dead: "exist",
  die: "exist",
  disappear: "exist",
  dream: "exist",
  effect: "exist",
  example: "exist",
  existence: "exist",
  factor: "exist",
  factory: "exist",
  grow: "exist",
  home: "exist",
  house: "exist",
  impact: "exist",
  incident: "exist",
  influence: "exist",
  instance: "exist",
  life: "exist",
  matter: "exist",
  nap: "exist",
  object: "exist",
  office: "exist",
  outcome: "exist",
  relax: "exist",
  remain: "exist",
  rest: "exist",
  room: "exist",
  shop: "exist",
  situation: "exist",
  sleep: "exist",
  stay: "exist",
  stuff: "exist",
  temple: "exist",
  thing: "exist",
  thrive: "exist",
  wake: "exist",

  // Art / Culture (extended)
  artistic: "art",
  band: "art",
  buddhist: "art",
  catholic: "art",
  celebrate: "art",
  celebration: "art",
  ceremony: "art",
  christian: "art",
  concert: "art",
  cultural: "art",
  dancer: "art",
  drama: "art",
  episode: "art",
  exhibit: "art",
  faith: "art",
  fashion: "art",
  festival: "art",
  god: "art",
  heritage: "art",
  hindu: "art",
  legend: "art",
  meditation: "art",
  musical: "art",
  muslim: "art",
  myth: "art",
  orthodox: "art",
  paint: "art",
  performance: "art",
  play: "art",
  prayer: "art",
  protestant: "art",
  religion: "art",
  religious: "art",
  ritual: "art",
  sacred: "art",
  scene: "art",
  sequel: "art",
  sing: "art",
  singer: "art",
  spiritual: "art",
  style: "art",
  theological: "art",
  tradition: "art",
  traditional: "art",
  worship: "art",

  // Create / Make (extended)
  accommodation: "create",
  architectural: "create",
  arrangement: "create",
  barracks: "create",
  blend: "create",
  bunker: "create",
  canal: "create",
  castle: "create",
  combination: "create",
  composition: "create",
  configuration: "create",
  creativity: "create",
  dam: "create",
  deal: "create",
  door: "create",
  effort: "create",
  facility: "create",
  floor: "create",
  fortress: "create",
  gate: "create",
  handle: "create",
  infrastructure: "create",
  integration: "create",
  invention: "create",
  layout: "create",
  memorial: "create",
  mixture: "create",
  monument: "create",
  palace: "create",
  procedure: "create",
  project: "create",
  railroad: "create",
  railway: "create",
  residential: "create",
  roof: "create",
  statue: "create",
  structure: "create",
  synthesis: "create",
  technique: "create",
  tower: "create",
  trench: "create",
  tunnel: "create",
  wall: "create",
  window: "create",

  // Fight / Conflict (extended)
  bend: "fight",
  blast: "fight",
  catch: "fight",
  collision: "fight",
  compete: "fight",
  confront: "fight",
  crack: "fight",
  crush: "fight",
  drag: "fight",
  drop: "fight",
  explosion: "fight",
  grab: "fight",
  grip: "fight",
  guard: "fight",
  hang: "fight",
  hit: "fight",
  kick: "fight",
  lift: "fight",
  load: "fight",
  oppose: "fight",
  pressure: "fight",
  protect: "fight",
  pull: "fight",
  push: "fight",
  resist: "fight",
  shock: "fight",
  split: "fight",
  squeeze: "fight",
  strain: "fight",
  stress: "fight",
  stretch: "fight",
  strike: "fight",
  struggle: "fight",
  tension: "fight",
  throw: "fight",
  twist: "fight",

  // Send / Communicate (extended)
  advertise: "send",
  advertisement: "send",
  announcement: "send",
  blog: "send",
  channel: "send",
  comment: "send",
  communication: "send",
  convince: "send",
  correspond: "send",
  cry: "send",
  display: "send",
  edition: "send",
  encourage: "send",
  forum: "send",
  information: "send",
  inspire: "send",
  introduce: "send",
  invite: "send",
  journalism: "send",
  letter: "send",
  motivate: "send",
  news: "send",
  newspaper: "send",
  persuade: "send",
  podcast: "send",
  press: "send",
  promise: "send",
  propaganda: "send",
  publication: "send",
  remark: "send",
  report: "send",
  show: "send",
  signal: "send",
  threaten: "send",

  // Write (extended)
  archive: "write",
  article: "write",
  book: "write",
  bookstore: "write",
  chapter: "write",
  column: "write",
  dialogue: "write",
  editorial: "write",
  essay: "write",
  fiction: "write",
  genre: "write",
  headline: "write",
  journal: "write",
  magazine: "write",
  manuscript: "write",
  narrative: "write",
  paper: "write",
  paragraph: "write",
  plot: "write",
  poetry: "write",
  prose: "write",
  story: "write",
  theme: "write",
  translation: "write",

  // Feel / Want / Need (extended)
  anxiety: "feel",
  avoid: "feel",
  care: "feel",
  compassion: "feel",
  crave: "feel",
  delight: "feel",
  demand: "feel",
  depression: "feel",
  emotional: "feel",
  empathy: "feel",
  enjoy: "feel",
  expect: "feel",
  gratitude: "feel",
  lack: "feel",
  miss: "feel",
  request: "feel",
  require: "feel",
  seek: "feel",
  suffer: "feel",
  sympathy: "feel",
  touch: "feel",
  worry: "feel",

  // Work / Enable (extended)
  accomplish: "work",
  achieve: "work",
  aid: "work",
  allow: "work",
  assist: "work",
  attempt: "work",
  contribute: "work",
  enable: "work",
  facilitate: "work",
  fail: "work",
  help: "work",
  serve: "work",
  succeed: "work",
  supply: "work",
  support: "work",
  toil: "work",
  try: "work",

  // Give (extended)
  allocate: "give",
  assign: "give",
  award: "give",
  defense: "give",
  ensure: "give",
  guarantee: "give",
  lend: "give",
  pass: "give",
  prevent: "give",
  protection: "give",
  refuge: "give",
  safety: "give",
  shelter: "give",

  // Speak (extended)
  answer: "speak",
  argue: "speak",
  ask: "speak",
  call: "speak",
  describe: "speak",
  mention: "speak",
  name: "speak",
  respond: "speak",
  shout: "speak",
  whisper: "speak",

  // Animal (extended)
  ape: "animal",
  breed: "animal",
  cattle: "animal",
  flock: "animal",
  hawk: "animal",
  herd: "animal",
  marine: "animal",
  mouse: "animal",
  pet: "animal",
  pig: "animal",

  // See (extended)
  examine: "see",
  gaze: "see",
  inspect: "see",
  monitor: "see",
  scan: "see",
  spot: "see",
  stare: "see",
  survey: "see",
  witness: "see",

  // Fix / Open (extended)
  close: "fix",
  lock: "fix",
  open: "fix",
  patch: "fix",
  recover: "fix",
  seal: "fix",
  shut: "fix",
  unlock: "fix",

  // Sport (extended)
  athletic: "sport",
  baseball: "sport",
  defeat: "sport",
  lose: "sport",
  swim: "sport",
  title: "sport",
  victory: "sport",
  win: "sport",

  // Plant (extended)
  beer: "plant",
  corn: "plant",
  grain: "plant",
  sugar: "plant",
  tea: "plant",
  tobacco: "plant",
  wheat: "plant",
  wine: "plant",

  // Food (extended)
  bite: "food",
  chew: "food",
  drink: "food",
  feed: "food",
  fruit: "food",
  swallow: "food",
  water: "food",

  // Weather (extended)
  air: "weather",
  disaster: "weather",
  drought: "weather",
  earthquake: "weather",
  flood: "weather",
  tide: "weather",
  wave: "weather",

  // Possess (extended)
  acquire: "possess",
  gain: "possess",
  get: "possess",
  have: "possess",
  obtain: "possess",
  receive: "possess",

  // Nature (extended)
  earth: "nature",
  fire: "nature",
  moon: "nature",
  sky: "nature",
  star: "nature",
  sun: "nature",

  // Destroy (extended)
  crash: "destroy",
  cut: "destroy",
  erase: "destroy",
  shatter: "destroy",
  tear: "destroy",

  // Connect (extended)
  detach: "connect",
  disconnect: "connect",
  fasten: "connect",
  separate: "connect",
  tie: "connect",

  // Measure (extended)
  compare: "measure",
  compute: "measure",
  rank: "measure",
  weigh: "measure",

  // Gather (extended)
  assembly: "gather",
  conference: "gather",
  convention: "gather",
  session: "gather",

  // Material (extended)
  brick: "material",
  cement: "material",
  cloth: "material",
  ink: "material",

  // Body (extended)
  face: "body",
};

// Suffix → role (longest-first)
const SUFFIX_ROLES: Array<[string, string]> = [
  // ── Arabic-origin أوزان roles — longest compound suffixes first ──
  ["ification", "process"], // simplification, electrification, qualification
  ["ization", "process"], // modernization, digitization, centralization
  ["aholic", "intensifier"], // workaholic, shopaholic (compulsive agent)
  ["seeker", "seeker"], // jobseeker, peaceseeker, truthseeker
  ["hunter", "seeker"], // headhunter, bargainhunter
  ["master", "intensifier"], // webmaster, grandmaster, toastmaster
  ["ifier", "causer"], // simplifier, purifier, amplifier, clarifier
  ["izer", "causer"], // modernizer, organizer, stabilizer
  // ── Standard English suffixes ──
  ["tion", "instance"],
  ["sion", "instance"],
  ["ment", "instance"],
  ["ance", "instance"],
  ["ence", "instance"],
  ["ness", "state"],
  ["able", "possible"],
  ["ible", "possible"],
  ["less", "negate"],
  ["ing", "process"],
  ["ful", "has"],
  ["ery", "place"],
  ["ory", "place"],
  ["ary", "place"],
  ["age", "instance"],
  ["ist", "agent"],
  ["ian", "agent"],
  ["ity", "state"],
  ["ify", "causer"], // simplify, clarify, modify (causative verb)
  ["ize", "causer"], // organize, modernize, realize (causative verb)
  ["ant", "seeker"], // applicant, aspirant, contestant
  ["er", "agent"],
  ["or", "agent"],
  ["ee", "patient"],
  ["ly", "manner"],
  ["al", "quality"],
  ["ed", "past"],
  ["s", "plural"],
];

// Prefix → role
const PREFIX_ROLES: Record<string, string> = {
  un: "negate",
  non: "negate",
  dis: "negate",
  re: "repeat",
  pre: "before",
  mis: "wrong",
  over: "excess", // overcharge, overload, overreact
  hyper: "excess", // hypersensitive, hyperactive (Arabic فوق)
  co: "mutual",
  out: "exceed",
};

// Relation words
const RELATION_MAP: Record<string, string> = {
  to: "REL:to",
  toward: "REL:to",
  towards: "REL:to",
  from: "REL:from",
  with: "REL:with",
  without: "REL:without",
  so: "REL:causes",
  since: "REL:causes",
  before: "REL:before",
  after: "REL:after",
  during: "REL:during",
  in: "REL:in",
  at: "REL:at",
  by: "REL:by",
  for: "REL:for",
  of: "REL:of",
  about: "REL:about",
  and: "REL:and",
  or: "REL:or",
  but: "REL:but",
  whether: "REL:condition",
  that: "REL:that",
  although: "REL:contrast",
  though: "REL:contrast",
  however: "REL:contrast",
  while: "REL:contrast",
  on: "REL:on",
  into: "REL:into",
  through: "REL:through",
  between: "REL:between",
  among: "REL:among",
  like: "REL:like",
  than: "REL:compare",
  as: "REL:as",
  via: "REL:via",
  per: "REL:per",
};

// Structural markers
const STRUCTURAL_MAP: Record<string, TokenType> = {
  not: "NEG",
  no: "NEG",
  never: "NEG",
  neither: "NEG",
  nor: "NEG",
  nothing: "NEG",
  nobody: "NEG",
  nowhere: "NEG",
  "?": "QUERY",
  what: "WHAT_Q",
  which: "WHICH_Q",
  where: "WHERE_Q",
  when: "WHEN_Q",
  who: "WHO_Q",
  why: "WHY_Q",
  how: "HOW_Q",
  if: "COND",
  unless: "COND",
  because: "CAUSE",
  therefore: "CAUSE",
  thus: "CAUSE",
  will: "FUTURE",
  shall: "FUTURE",
  would: "FUTURE",
  can: "MODAL",
  could: "MODAL",
  may: "MODAL",
  might: "MODAL",
  must: "MODAL",
  should: "MODAL",
  was: "PAST",
  were: "PAST",
  had: "PAST",
  // Negated contractions
  "can't": "NEG",
  cannot: "NEG",
  "don't": "NEG",
  "doesn't": "NEG",
  "didn't": "NEG",
  "won't": "NEG",
  "isn't": "NEG",
  "aren't": "NEG",
  "wasn't": "NEG",
  "weren't": "NEG",
  "haven't": "NEG",
  "hasn't": "NEG",
  "hadn't": "NEG",
  "shouldn't": "NEG",
  "wouldn't": "NEG",
  "couldn't": "NEG",
  "mustn't": "NEG",
  "needn't": "NEG",
  "shan't": "NEG",
};

// Function words (dropped)
const FUNCTION_WORDS = new Set([
  "the",
  "a",
  "an",
  "is",
  "are",
  "be",
  "been",
  "being",
  "am",
  "i",
  "you",
  "he",
  "she",
  "it",
  "we",
  "they",
  "me",
  "him",
  "her",
  "us",
  "them",
  "my",
  "your",
  "his",
  "its",
  "our",
  "their",
  "this",
  "that",
  "these",
  "those",
  "there",
  "here",
  "do",
  "does",
  "did",
  "has",
  "have",
  "very",
  "quite",
  "just",
  "also",
  "even",
  "only",
  "still",
  "then",
]);

// ── Compound bigrams (checked before single-word lookup) ─────────────────────

export const COMPOUND_FIELDS: Record<string, string> = {
  // Tech / AI
  "machine learning": "know",
  "artificial intelligence": "think",
  "deep learning": "know",
  "neural network": "tech",
  "natural language": "speak",
  "source code": "tech",
  "version control": "hold",
  "operating system": "tech",
  "user interface": "tech",
  "web page": "tech",
  "home page": "tech",
  "search engine": "see",
  "file system": "hold",
  "data science": "science",
  "open source": "give",
  // Health
  "blood pressure": "health",
  "heart rate": "health",
  "blood sugar": "health",
  "blood test": "health",
  "side effect": "health",
  "first aid": "health",
  "physical therapy": "health",
  "mental health": "health",
  "food safety": "health",
  // Science
  "black hole": "science",
  "solar system": "science",
  "climate change": "weather",
  "global warming": "weather",
  // Coding
  "bug fix": "fix",
  "bug report": "fix",
  "code review": "see",
  "pull request": "create",
  // Finance
  "stock market": "trade",
  "exchange rate": "trade",
  "interest rate": "trade",
  "income tax": "trade",
  // Time
  "real time": "time",
  "time zone": "time",
  "due date": "time",
  // Sport
  "world cup": "sport",
  // Fight
  "civil war": "fight",
  // Social
  "social media": "send",
};

// ── Morphology helpers ────────────────────────────────────────────────────────

function resolveField(word: string): string | undefined {
  const w = word.toLowerCase();

  // 1. Direct lookup
  if (SEMANTIC_FIELDS[w]) return SEMANTIC_FIELDS[w];
  // 2. Silent-e restoration ("writ" → "write")
  if (SEMANTIC_FIELDS[w + "e"]) return SEMANTIC_FIELDS[w + "e"];

  // 3. Single suffix strip + silent-e
  for (const [suffix] of SUFFIX_ROLES) {
    if (w.endsWith(suffix) && w.length > suffix.length + 2) {
      const stem = w.slice(0, w.length - suffix.length);
      const f = SEMANTIC_FIELDS[stem] ?? SEMANTIC_FIELDS[stem + "e"];
      if (f) return f;

      // 4. Nested: strip a second suffix from the stem
      //    e.g. "readable" → strip "able" → "read" → field "know"
      //         "organization" → strip "tion" → "organiza" → strip "ize" → "organ" (no hit)
      //         "simplification" → strip "ification" → "simpl" → strip "ify" etc.
      for (const [suffix2] of SUFFIX_ROLES) {
        if (stem.endsWith(suffix2) && stem.length > suffix2.length + 2) {
          const stem2 = stem.slice(0, stem.length - suffix2.length);
          const f2 = SEMANTIC_FIELDS[stem2] ?? SEMANTIC_FIELDS[stem2 + "e"];
          if (f2) return f2;
        }
      }
    }
  }

  // 5. Prefix strip fallback — strip known prefix, resolve the bare stem
  //    e.g. "disorganize" → "organize" → "work"
  //         "rewrite" → "write"
  for (const prefix of Object.keys(PREFIX_ROLES)) {
    if (w.startsWith(prefix) && w.length > prefix.length + 2) {
      const stem = w.slice(prefix.length);
      const f = SEMANTIC_FIELDS[stem] ?? SEMANTIC_FIELDS[stem + "e"];
      if (f) return f;
    }
  }

  return undefined;
}

function detectRole(word: string): string | undefined {
  const w = word.toLowerCase();
  for (const [suffix, role] of SUFFIX_ROLES) {
    if (w.endsWith(suffix) && w.length > suffix.length + 2) return role;
  }
  for (const [prefix, role] of Object.entries(PREFIX_ROLES)) {
    if (w.startsWith(prefix) && w.length > prefix.length + 2) return role;
  }
  return undefined;
}

// ── Core tokenizer ────────────────────────────────────────────────────────────

/** Convert an English sentence into CST reasoning-mode tokens. */
export function tokenize(sentence: string): CSTToken[] {
  const tokens: CSTToken[] = [];
  const words = sentence.replace(/[?!.]+$/, "").split(/\s+/);

  if (sentence.trimEnd().endsWith("?")) {
    tokens.push({ type: "QUERY", value: "QUERY", surface: "?" });
  }

  // Pre-scan: mark word indices consumed by a compound bigram
  const skipIdx = new Set<number>();
  for (let i = 0; i < words.length - 1; i++) {
    const w0 = words[i].toLowerCase().replace(/^[.,;:!?"']+|[.,;:!?"']+$/g, "");
    const w1 = words[i + 1]
      .toLowerCase()
      .replace(/^[.,;:!?"']+|[.,;:!?"']+$/g, "");
    const compound = `${w0} ${w1}`;
    if (COMPOUND_FIELDS[compound]) {
      skipIdx.add(i);
      skipIdx.add(i + 1);
      tokens.push({
        type: "CONCEPT",
        value: `CONCEPT:${COMPOUND_FIELDS[compound]}`,
        surface: `${words[i]} ${words[i + 1]}`,
        field: COMPOUND_FIELDS[compound],
      });
    }
  }

  for (let idx = 0; idx < words.length; idx++) {
    if (skipIdx.has(idx)) continue;
    const word = words[idx];
    const w = word.toLowerCase().replace(/^[.,;:!?"']+|[.,;:!?"']+$/g, "");
    if (!w) continue;

    const structural = STRUCTURAL_MAP[w];
    if (structural) {
      tokens.push({ type: structural, value: structural, surface: word });
      continue;
    }

    const rel = RELATION_MAP[w];
    if (rel) {
      tokens.push({ type: "REL", value: rel, surface: word });
      continue;
    }

    if (FUNCTION_WORDS.has(w)) continue;

    const field = resolveField(w);
    const role = detectRole(w);

    if (field && role) {
      tokens.push({
        type: "CONCEPT",
        value: `CONCEPT:${field}`,
        surface: word,
        field,
      });
      tokens.push({ type: "ROLE", value: `ROLE:${role}`, surface: word, role });
    } else if (field) {
      tokens.push({
        type: "CONCEPT",
        value: `CONCEPT:${field}`,
        surface: word,
        field,
      });
    } else if (role) {
      tokens.push({ type: "ROLE", value: `ROLE:${role}`, surface: word, role });
    } else {
      tokens.push({ type: "LIT", value: `LIT:${w}`, surface: word });
    }
  }

  return tokens;
}

/** Human-readable token stream string. */
export function tokenStream(sentence: string): string {
  return tokenize(sentence)
    .map((t) => t.value)
    .join(" ");
}
